### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by ninjamask**
Three strings missing because I don't know what it does or where its used.

Missing:
```
    <string name="secure_screen">Secure screen</string>
    <string name="hide_tachi_from_recents">Hide Tachiyomi from the recents screen</string>
    <string name="drag_handle">Drag handle</string>
```

### CODE REVIEW

**Comment by Jays2Kings** [comment]
`secure_screen` and `hide_tachi_from_recents` relate to to the setting in general, which hides tachiyomi from the recent apps screen.

`drag_handle` is used for the descption of the 2 lines that are used to drag downloads or categories up and down:
baseline_drag_handle_black_18dp

**Comment by ninjamask** [comment]
Sorry for this mess. I lack Github knowledge.

I translated the missing and new strings.

**Comment by ninjamask** [comment]
`<string name="migration_sources_set">Migration sources set</string>` ?

**Comment by Jays2Kings** [comment]
There is an option to change the migration sources used. They are _set_ to a new list this the message is to say that the migration sources are set.

This can also be "migration sources changed", which I might switch that verbage too

**Pull request merged**
