### PR TITLE
Russian types manga (without forced switching type reader)

### PR DESCRIPTION
**Pull request by e-shl**

### CODE REVIEW

**Comment by e-shl** [comment]
Apologize for the excess Commits

**Comment by e-shl** [comment]
Why there is no manga filter in the library? (only manhwa / manhua / comic)

**Comment by e-shl** [comment]
Supported Russian  sources https://github.com/inorichi/tachiyomi-extensions/commit/252d72c204ae2b78087cdbac52afe35602bab174

**Comment by Jays2Kings** [comment]
Manga tag isn't a filter because other sources don't have proper tagging so manga is a default rather that a true comic type

**Comment by e-shl** [comment]
@Jays2Kings I specifically added a manga tag to Russian sources.  can you add filtering?

**Comment by Jays2Kings** [comment]
The manga tag is just for displaying "about this manga" correctly. I've already given a reason as to why I rather not add it, but it's better discussed in a feature request ticket, rather than a closed pr

**Pull request merged**
