### PR TITLE
Material 3

### PR DESCRIPTION
**Pull request by Jays2Kings**
| Material 3 | Material 2 |
| ---      | ---       |
| Screenshot_20210912-191458 |  Screenshot_20210912-191502 |
| Screenshot_20210912-191655 | Screenshot_20210912-191705 |
| Screenshot_20210912-191515 | Screenshot_20210912-191513 |
| Screenshot_20210912-191528 | Screenshot_20210912-191531 |
| Screenshot_20210912-191616 | Screenshot_20210912-191631 |
| Screenshot_20210912-191730 | Screenshot_20210912-191735 |
| Screenshot_20210912-191757 | Screenshot_20210912-191800 |
| Screenshot_20210912-192023 | Screenshot_20210912-192030 |
| Screenshot_20210912-192431 | Screenshot_20210912-192455 |

Also removed material dialogs lib in place of the native solution

Other changes (somewhat related M3):
- Fixes to color primary for most themes
- Added new colors for colorPrimaryInverse (used for snackbar action + inverted reader background to main theme)
- Showing manga title in info when scrolling
- No more elevation and shadows for the most part, instead the toolbar color will change when scrolling down

- ~Also targeting A12~

### CODE REVIEW

**Comment by Jays2Kings** [comment]
More updates:
| Info | Material 3 | Material 2 |
| ---     | ---      | ---       |
| Update bottom nav + tab chip highlights suggested by @CrepeTF | Screenshot_20210919-145115 | Screenshot_20210919-145118 |
| Updates to the library badges | Screenshot_20210919-145226 | Screenshot_20210919-145222 |
| Dark theme | Screenshot_20210919-145501 | Screenshot_20210919-145446 |
| Updated backdrops color tint, now way less prominent | Screenshot_20210919-145234 | Screenshot_20210919-145230 |
| Dark theme | Screenshot_20210919-151035 | Screenshot_20210919-151032 |

**Comment by Jays2Kings** [comment]
Likely the final update before merging/waiting for M3 beta 01, final updates to manga details. It is now themed by the manga cover (optional before anyone asks), buttons are slightly bigger etc

(Note: Both are using the same Android 12 Monet theme with a blue tint)
| Material 3 | Material 2 |
| ---     | ---      |
| Screenshot_20210924-014549 | Screenshot_20210924-014545 |
| Screenshot_20210924-014600 | Screenshot_20210924-014603 |
| Screenshot_20210924-014738 | Screenshot_20210924-014734 |
| Screenshot_20210924-014801 | Screenshot_20210924-014758 |
| Screenshot_20210924-020334 | Screenshot_20210924-020339 |
| Screenshot_20210924-020519 | Screenshot_20210924-020526 |

**Comment by CarlosEsco** [comment]
Few comments 
1.  Backdrop color :sob:  Since it seems you are calculating the color for the buttons (for matching the cover), why not use that color for the backdrop.
2.  Personally the old popped out style unread badge looked better

**Comment by CarlosEsco** [comment]
also a squash merge before pulling in the latest scanlator changes from master would be preferred :laughing:

**Comment by Jays2Kings** [comment]
> Few comments
> 
> 1. Backdrop color 😭  Since it seems you are calculating the color for the buttons (for matching the cover), why not use that color for the backdrop.
> 2. Personally the old popped out style unread badge looked better

1. I lowered the how much the influence is on the backdrop and used the dominant color, but it doesnt seem to look like it has an effect most places, I'll try to find a middle ground for it
2. As for the badges, I'll have to take a vote on because I'm indecisive for them and the slight boost in real estate isnt bad at all

> also a squash merge before pulling in the latest scanlator changes from master would be preferred 😆

Too late now lol, there's still a couple more fixes left for this and might do one last release before a merge

**Comment by CarlosEsco** [comment]
my concern with the badges are they blend into the cover more, and don't look like badges (for example the 1 on the browse bottom nav)

My other suggestion is a middle ground on the light theme?  MD2 the search bar and bottom nav are a bit too light and blend in, on MD3 the contrast seems a bit too much  (this is referring to the screen with TF's suggested changes)

**Comment by Jays2Kings** [comment]
Sure I'll try to find a middle ground for both in due time

**Pull request merged**
