### PR TITLE
Some Detail UI changes

### PR DESCRIPTION
**Pull request by CarlosEsco**
Added more margin more, less, details buttons since fast scroller was causing them to look bad

image

to 

image

made gradient slightly longer most noticeable in amoled mode
image

to

image

Lastly which maybe you dont agree with but the title bar with the manga title looks weird in the initial scenario and ideally the user shouldnt need reminding they are on a specific manga
image

to 

image

### CODE REVIEW

**Comment by arkon** [comment]
Maybe show the toolbar title when it's scrolled up?

**Comment by Jays2Kings** [comment]
> Maybe show the toolbar title when it's scrolled up?

That's currently how it is, if you scroll down it shows when the toolbar shows up again (when you scroll back upwards)

**Comment by CarlosEsco** [comment]
Maybe it's bugged then. If I scroll down slow with small amount. Then stop it shows title even though I haven't scrolled up

**Comment by Jays2Kings** [comment]
No you're right it also shows if you stop mid scroll since there's no nice way to no the offset from the top of the recycler, I think the change is fine, however with the margin change, the fast scroll should just always show then. 

If you agree with that I can adjust it to always show then

**Comment by CarlosEsco** [comment]
Fast scroll should stay hidden as some shorter manga all fit 1 page.

**Pull request merged**
