### PR TITLE
Language badges in library (flags)

### LINKED ISSUE #616: [Feature Request]Display source language(ISO 639-1 Code)badge
### Why/User Benefit/User Problem
It will be convenient for polyglot user who want to read a manga in a specific language

### What/Requirements
_Option to display source language badge(ISO 639-1 Code)

### PR DESCRIPTION
**Pull request by nzoba**
This PR contains:

- Add language badges (flags) in library (inspired from original Tachiyomi, activable via *Display options > Badges* in library).
I removed the strokes around the flags from the previous PR. I thought about just displaying text but it was more of a hassle to get a decent badge that went well with the unread and download badges so I opted for the flags and I kind of like the result personally. (Closes #616 but with flags)

| Flags in grid layout | Flags in list layout |
|----|----|
| Flags in grid layout  | Flags in list layout |

### CODE REVIEW

**Comment by Jays2Kings** [comment]
Sorry I've been ignoring the prs, but I think it's better to just use text like og tachi. I would rather the flags been in the badge either as a 3rd section or on the right side of the grid covers, but 
1) images are just making the app larger for a feature most might not use
2) the flags won't be accurate anyway, English comics might be from the UK, might be from the US, or another English speaking country, same with Spanish or other languages

I'm not sure if you want to attempt the idea of adding a 3rd part to the download/unread badge but if you do I'll accept the flags anyway (even though I still prefer just text), if you don't it's nbd, as I had planned to add language tags regardless

**Comment by nzoba** [comment]
Thanks for your feedback !
At first I also wanted to do that but like I mentionned in my original message, it was more complicated to make the text go well with the already existing badges (I didn't try that much tbh). So I chose the easy way out : the flags, and tbh I kinda like the end result even though I was not convinced at first.

1. I actually didn't think about that at all, I thought some xml drawables weren't that much but I don't know much about it so it may be more of a problem than I thought
2. Yes that's right that was my main point of hesitation. I decided to use most of mangadex flags when available, and I chose the most iconic flag (totally biased) since most sources are based on a language, not a country, anyway. But you are right it's not an ideal solution

I won't attempt the text version since I think it would take me way too much time (I don't have much experience) so I'll let you decide what you want to do with my PR. But I can change whatever you feel is necessary (or feel free to do so to match your preferences)

**Comment by Jays2Kings** [comment]
Keep the pr open, I'll try to approach im thinking of with the flags just for you. I'll use this pr as a base if anything

**Comment by Jays2Kings** [comment]
I managed to get a decent look down so I'll post it to you before I directly commit it to master. If it's fine with you I'll commit.

**Comment by nzoba** [comment]
Looks awesome, great job !

**Comment by Jays2Kings** [comment]
Closing this since its now committed. Thanks again 👍

**Comment by arkon** [comment]
Where's my Canadian flags smh /s

**Comment by Jays2Kings** [comment]
I'm so sorry to be the one to tell you but... Canada's not real

**Comment by CarlosEsco** [comment]
Don't understand the 2 way split.  England flag can pound sand.  That or I request a customizable flag so I can choose which English flag I want to see 😄

**Comment by Jays2Kings** [comment]
> Don't understand the 2 way split.  England flag can pound sand.  That or I request a customizable flag so I can choose which English flag I want to see 😄 

Lol I did later add a separate full US and UK flag, that shows for English (US) and (UK) respectively, so that split will only show for someone in another locale

**Pull request closed without merging**
