### PR TITLE
Update ShikimoriApi.kt

### PR DESCRIPTION
**Pull request by VlasovRoman**
shikimori.ME changed for shikimori.ONE

### CODE REVIEW

**Comment by Jays2Kings** [comment]
both urls seem to still work, i also dont see the change on main tachi so im unsure about this change

**Comment by e-shl** [comment]
> both urls seem to still work, i also dont see the change on main tachi so im unsure about this change

.ME is blocked in Russia
need to apply to main tachi

**Comment by Jays2Kings** [comment]
I'll wait for main tachi to merge first

**Comment by VlasovRoman** [comment]
> I'll wait for main tachi to merge first

https://github.com/tachiyomiorg/tachiyomi/pull/10027

**Pull request merged**
